version: "3.0"

services:
    influxdb:
        container_name: power_meter_influxdb
        image: influxdb
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_USER=root
            - INFLUXDB_PASS=root

    telegraf:
        container_name: power_meter_telegraf
        image: telegraf
        network_mode: "host"
        volumes:
            - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /proc:/host/proc:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "6515:6514"

    mosquitto:
        container_name: power_meter_mosquitto
        image: eclipse-mosquitto
        user: "0"
        network_mode: "host"
        volumes:
            - ./etc/mosquitto.conf:/etc/mosquitto/mosquitto.conf:ro
            - ./etc/mqtt-server.pem:/etc/mosquitto/mqtt-server.pem:ro
            - ./etc/mqtt-server.crt:/etc/mosquitto/mqtt-server.crt:ro
            - ./etc/ca.crt:/etc/mosquitto/ca.crt:ro
        ports:
            - "1883:1883"
            - "8883:8883"

    grafana:
        container_name: power_meter_grafana
        image: grafana/grafana
        environment:
            - NO_PROXY="influxdb"
        ports:
            - "3000:3000"
