version: "3.0"

services:
    influxdb:
        container_name: power_meter_influxdb
        image: influxdb
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_USER=root
            - INFLUXDB_PASS=root
        restart: always

    telegraf:
        container_name: power_meter_telegraf
        image: telegraf
        network_mode: "host"
        volumes:
            - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /proc:/host/proc:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: always

    mosquitto:
        container_name: power_meter_mosquitto
        image: eclipse-mosquitto
        user: "0"
        network_mode: "telegraf"
        ports:
            - "1883:1883"
        restart: always

    grafana:
        container_name: power_meter_grafana
        image: grafana/grafana
        environment:
            - NO_PROXY="influxdb"
        ports:
            - "3000:3000"
